name: find_work
description: This app my first project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  glassmorphism: ^3.0.0
  lottie: ^2.6.0
  device_preview: ^1.1.0
  image_picker: ^1.0.4
  shared_preferences: ^2.2.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  flutter_native_splash: ^2.3.3
  flutter_cache_manager: ^3.3.1
  gallery_saver: ^2.3.2
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  path: ^1.8.3
  http: ^0.13.6
  hive_flutter: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/lotties/
    - assets/image/
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

